### ISSUE TITLE
Breaking endpoints into seperate files

### ISSUE THREAD

**Issue by ilyas-shah** [JKHeadley/appy#1]
Just want know how can we divide endpoints into seperate files, for example in your api folder there are different files and each file contains different endpoints making the file size very huge, cant we have a separate folder like login in which i put different endpoint files like a separate file for reset password, seperate file for social logins etc???

**Comment by ilyas-shah** [comment]
if that is the case, it would be great to see that feature in Rest-Hapi, and that will be helpful to write unit tests for the individual endpoints. Also for now what do you suggest for Rest-Hapi endpoint unit testing?

**Comment by JKHeadley** [comment]
@ilyas-shah sorry for just getting back to you on this. To test generated endpoints you can use `RestHapi.testHelper.mockInjection` combined with `server.inject` to assist in mocking endpoint requests. You can see an example here: 
https://github.com/JKHeadley/rest-hapi/blob/09d2045edc90adbb464ca5f79f935a40d9a181ee/tests/e2e/end-to-end.tests.js#L551
