### ISSUE TITLE
Send mail with sendgrid

### ISSUE THREAD

**Issue by phmatray** [JKHeadley/appy#12]
Hello, 

What settings need to be changed in the configuration to send emails with SendGrid?
I tried with the user/pass couple and with the api_key but I can't get a conclusive result.

Do you have any ideas to help me solve this problem? I could possibly propose a pull request if I can find the solution.

**Comment by phmatray** [comment]
Thanks for the advices. :)
It works 👍

**Comment by JKHeadley** [comment]
Excellent! Glad to hear it.
