### ISSUE TITLE
Mongo TTL Error

### ISSUE THREAD

**Issue by elielam** [JKHeadley/appy#37]
Hello,

I follow the README instructions for non-docker installation.

I get an error when running backend.

`
MongoError: TTL index 'expireAfterSeconds' option must be numeric, but received a type of 'null'. Index spec: { name: "date_1", key: { date: 1 }, expireAfterSeconds: null, background: true }
`

I tried to change mongoose version but no effect on error.

MongoDB version : 4.2
Mongoose version : 5.0.9 & 5.0.4 ( error show with both )

Thank you in advance.

**Comment by JKHeadley** [comment]
@elielam this was an issue in rest-hapi. If you update to the latest version of rest-hapi (v1.9.1) this should be resolved.
