### ISSUE TITLE
Account activation link uses backend link instead of frontend

### ISSUE THREAD

**Issue by donblackowiak** [JKHeadley/appy#4]
Hi
Thank you for this sharing your work!

For version 1.0.0, in a local, npm install, the account activation link came as:
http://localhost:8080/activate?....
Which doesn't work until you change it to localhost:3000/activate?...  e.g. the frontend
Email below...
Don

```
Welcome Aboard

Thanks for signing up! You're almost done, please click on the link below within 24 hours to activate your account:

http://localhost:8080/activate?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJvYkBsdWN1bWEuY29tIiwia2V5IjoiYjc3OGQ3NzEtNGI5OC00NWEwLTk2MTMtZWFhMjUyNWVjNDVlIiwiaWF0IjoxNTMwOTk5NjQ4LCJleHAiOjE1MzEwODYwNDh9.onlHjT-l514zCfHdx_Dt5gIZVbgjXQs7rYqc_w6rf2M

Love,

The appy Admin Team
```

**Comment by jgarcia24n** [comment]
Change the env settings for the backend
CLIENT_URL=http://localhost:3000

**Comment by JKHeadley** [comment]
@donblackowiak thanks for pointing this out. @jgarcia24n has the correct solution. I've pushed an update to the example .env files.
