### ISSUE TITLE
Reset password page should redirect to login (potential fix found)

### ISSUE THREAD

**Issue by thomasqbrady** [JKHeadley/appy#42]
Brand new installation from this morning.

What I did to encounter error:

1. Create account. Verify email address.
2. Log in and log out.
3. Click "forgot password" from login page.
4. Fill in email and click "request link"
5. click link from email (I have verified the link includes a token and pinRequired=true).
6. put in new password (twice) and pin, click "reset password"
7. Page reloads and I get an error message that says "The link you used did not contain a token. Please click on the reset password link in your email or proceed to the login page to request a new email." I would expect to be redirected to the login page, or perhaps given a message that says "your password has been changed" and a link to the login page.

**Comment by thomasqbrady** [comment]
This took me way too long to figure out (probably because my debugging skills are a bit rusty, and I don't have a lot of Vue experience).

Currently in the form on the password reset page, there was no `@submit.prevent="onSubmit"` directive, so clicking "reset password" triggered a submit event, which triggered a page refresh, which triggered the view to load with a pin in the query string (a result of the form submission), which looked to the page init as though you were following an activation link, which appeared to be missing the token. Putting the `@submit.prevent="onSubmit"` seems to have fixed everything. This worth a pull request?

**Comment by JKHeadley** [comment]
@thomasqbrady Thanks for checking this out! If you don't mind creating a PR I would really appreciate it. 😄

**Comment by thomasqbrady** [comment]
@JKHeadley PR created: thomasqbrady:issue42
