### ISSUE TITLE
Failed to encode cookie (bell-facebook) value

### ISSUE THREAD

**Issue by devopsadmin-james** [JKHeadley/appy#46]
web_1    | > Listening at http://localhost:3000
web_1    | 

When i click on any of the available social login buttons, i receive below errors of this appy repo.
i'm using docker for this purpose.

api_1    | Debug: internal, implementation, error 
api_1    |     Error: Failed to encode cookie (bell-facebook) value: Password string too short (min 32 characters required)
api_1    |     at Object.exports.prepareValue (/backend/node_modules/@hapi/statehood/lib/index.js:452:20)
api_1    |     at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by JKHeadley** [comment]
@sysadmin-james I believe this is due to the default `FACEBOOK_SECRET` env var in your `.env-docker` being too short. Try setting it to something larger than 32 chars.  You might need to do this for the other secrets/tokens as well.

**Comment by devopsadmin-james** [comment]
just adding below key value pair in .env-docker file did the trick for me

SOCIAL_PASSWORD=abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz
