### ISSUE TITLE
backend api  update password error

### ISSUE THREAD

**Issue by jgarcia24n** [JKHeadley/appy#6]
The api backend api /user/my/password gives a 500 internal error,
Looked into the backend logs and its show its not returning a promise.
I looked into the  user.api.js and under the passwordCheck method I simply put a return null,
for now, and seems to be working fine. I don't what the correct way would be for this?

**Comment by JKHeadley** [comment]
@jgarcia24n thanks for pointing this out. I fixed the issue in the [latest commit](https://github.com/JKHeadley/appy/commit/20de2f42b8ed981f490e21170201c9e060f82a73).
