### ISSUE TITLE
[bug] seed ip address required

### ISSUE THREAD

**Issue by 1change** [JKHeadley/appy#7]
I needed to add
`visitor.ip = '123.123.123.123'`
in order to pass seed generation

**Comment by JKHeadley** [comment]
@1change what is the error output when you don't specify the ip?

**Comment by 1change** [comment]
It was validation saying ip is required in visitor model

**Comment by JKHeadley** [comment]
@1change there was a change in how geolocation data was retrieved with the 'iplocation' module. See https://github.com/JKHeadley/appy/commit/5abfc96055643d569b1cfcb7a43772b738aab7bb for a fix.

**Comment by 1change** [comment]
great thx
